Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.Extensions.Configuration;
using Dapper;
using LegalHunter.Data;
using LegalHunter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Newtonsoft.Json;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using Microsoft.AspNetCore.Http;
using ExcelDataReader;
using OfficeOpenXml;

namespace LegalHunter.Controllers
{
    [Authorize(Roles = "PlatformOwner")]
    public class ExamsController : Controller
    {
        readonly ApplicationDbContext db;
        private readonly IHostingEnvironment _env;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IMapper _mapper;
        private readonly IConfiguration _configuration;
        private readonly string _connectionString;
        public ExamsController(IHostingEnvironment env, IMapper mapper, ApplicationDbContext Context, UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> SignInManager, IConfiguration configuration)
        {
            _env = env;
            db = Context;
            _userManager = userManager;
            _signInManager = SignInManager;
            _mapper = mapper;
            _configuration = configuration;
            _connectionString = _configuration.GetConnectionString("DefaultConnection");
        }

        public IActionResult Index()
        {
            return View();
        }
        #region Exam
        [Authorize(Roles = "PlatformOwner")]
        public IActionResult Exam(int ExamID, string Option)
        {
            ViewBag.ExamCategoryList = GetCategoryData();
            ExamViewModel Exam = new ExamViewModel();
            try
            {
                if (Option == "Edit")
                {
                    var ExamDetails = db.ExamTbl.Where(x => x.ExamID == ExamID).FirstOrDefault();
                    Exam = _mapper.Map<ExamViewModel>(ExamDetails);
                    Exam.Option = "Edit";
                }
                else
                {
                    Exam.ExamCategoryIDf = 1;

                }
            }
            catch (Exception ex)
            {
                HelperStoreSqlLog.WriteError(ex, "Error - LegalHunter");
            }
            return View(Exam);
        }

        [Authorize(Roles = "PlatformOwner")]
        [HttpPost]
        public async Task<IActionResult> Exam(ExamViewModel PostObject)
        {
            ViewBag.ExamCategoryList = db.CategoryTbl.Where(x => x.IsActive == true && x.IsDelete == false).ToList();
            try
            {
                int ExamIDtoUpdate;
                if (PostObject.Option == "Edit")
                {
                    ExamIDtoUpdate = PostObject.ExamID;
                }
                else
                {
                    Exam NewObject = new Exam();
                    NewObject.ExamCreatedBy = GetUserID();
                    NewObject.ExamCreatedOn = Common.GetCurrentDateTime();
                    NewObject.ExamCreatedByBranchID = 1;
                    NewObject.IsActive = true;
                    NewObject.IsDelete = false;
                    db.ExamTbl.Add(NewObject);
                    db.SaveChanges();
                    ExamIDtoUpdate = NewObject.ExamID;
                }
                var ExamUpdate = db.ExamTbl.Where(x => x.ExamID == ExamIDtoUpdate).FirstOrDefault();
                ExamUpdate.ExamName = PostObject.ExamName;
                ExamUpdate.ExamCategoryIDf = 1;
                ExamUpdate.ExamDuration = PostObject.ExamDuration;
                ExamUpdate.ExamDesc = PostObject.ExamDesc;
                db.SaveChanges();
                TempData["AlertStatus"] += Common.GenerateNotification("Exam Updated Successfully", "success");
                return RedirectToAction("ExamList");

            }
            catch (Exception ex)
            {
                HelperStoreSqlLog.WriteError(ex, "Error - LegalHunter");
                TempData["AlertStatus"] += Common.GenerateNotification("Exam Update-Error", "danger");
                return View(PostObject);
            }
        }


        [Authorize(Roles = "PlatformOwner")]
        public IActionResult ExamList()
        {
            return View();
        }


        [AllowAnonymous]
        public string SearchExam()
        {
            string limit, start, searchKey, orderColumn, orderDir, draw, jsonString, filterType;
            limit = HttpContext.Request.Form["length"].FirstOrDefault();
            start = HttpContext.Request.Form["start"].FirstOrDefault();
            searchKey = HttpContext.Request.Form["search[value]"].FirstOrDefault();
            //  filterType = HttpContext.Request.Form["search[value]"].FirstOrDefault();
            orderColumn = HttpContext.Request.Form["order[0][column]"].FirstOrDefault();
            orderDir = HttpContext.Request.Form["order[0][dir]"].FirstOrDefault();
            draw = HttpContext.Request.Form["draw"].FirstOrDefault();

            using (IDbConnection conn = new SqlConnection(_connectionString))
            {

                var reader = conn.QueryMultiple("SearchExam", param: new { orderColumn = orderColumn, limit = limit, orderDir = orderDir, start = start, searchKey = searchKey }, commandType: CommandType.StoredProcedure);

                var ExamSearchList = reader.Read<ExamSearchModel>().ToList();

                int count = 0;
                if (ExamSearchList.Count > 0)
                {
                    count = ExamSearchList.FirstOrDefault().TotalCount;
                }
                dynamic newtonresult = new
                {
                    status = "success",
                    draw = Convert.ToInt32(draw == "" ? "0" : draw),
                    recordsTotal = count,
                    recordsFiltered = count,
                    data = ExamSearchList
                };
                jsonString = JsonConvert.SerializeObject(newtonresult);

                return jsonString;
            }

        }

        public class ExamSearchModel : ExamViewModel
        {
            public int TotalCount { get; set; }
            public string ExamCategoryName { get; set; }
            public string CreatedOnString { get; set; }

        }

        [Authorize(Roles = "PlatformOwner")]
        public ActionResult examStatus(int id, bool Status)
        {
            try
            {


                var ExamDetails = db.ExamTbl.Where(x => x.ExamID == id).FirstOrDefault();

                if (ExamDetails != null)
                {
                    //db.RawMaterialTbls.Remove(CheckRawMaterial); USED FOR DELETE FROM PROJECT
                    ExamDetails.IsActive = Status;
                    db.SaveChanges();
                    TempData["AlertStatus"] += Common.GenerateNotification("Exam Status Updated Successfully", "warning");
                    return RedirectToAction("ExamList");
                }
                else
                {
                    TempData["AlertStatus"] += Common.GenerateNotification("Exam Status Update-Error", "danger");
                    return RedirectToAction("ExamList");
                }
            }
            catch (Exception ex)
            {
                HelperStoreSqlLog.WriteError(ex, "Error - Legal Hunter");
                return RedirectToAction("ExamList");
            }


        }
        [Authorize(Roles = "PlatformOwner")]
        public IActionResult DeleteExam(int id)
        {
            try
            {


                var ExamDetails = db.ExamTbl.Where(x => x.ExamID == id).FirstOrDefault();

                if (ExamDetails != null)
                {
                    //db.RawMaterialTbls.Remove(CheckRawMaterial); USED FOR DELETE FROM PROJECT
                    ExamDetails.IsActive = false;
                    ExamDetails.IsDelete = true;
                    db.SaveChanges();
                    TempData["AlertStatus"] += Common.GenerateNotification("Exam Status Deleted Successfully", "warning");
                    return RedirectToAction("ExamList");
                }
                else
                {
                    TempData["AlertStatus"] += Common.GenerateNotification("Exam Status Delete-Error", "danger");
                    return RedirectToAction("ExamList");
                }
            }
            catch (Exception ex)
            {
                HelperStoreSqlLog.WriteError(ex, "Error - Legal Hunter");
                return RedirectToAction("ExamList");
            }
        }
        public IActionResult DownloadAnswerKey(int id)
        {
            var ExamAnswerKey = from items in db.ExamQuestionsMapTbl where items.ExamIDf == id select new { QuestionNo = items.ExamQuestionNo, Answer = items.CorrectOption };
            var stream = new MemoryStream();
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage(stream))
            {
                var workSheet = package.Workbook.Worksheets.Add("Sheet1");
                workSheet.Cells.LoadFromCollection(ExamAnswerKey, true);
                package.Save();
            }
            stream.Position = 0;
            string excelName = $"AnswerKey-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";

            //return File(stream, "application/octet-stream", excelName);  
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
        }
        #endregion

        #region Bulk Question Upload
        [HttpPost]
        [RequestFormLimits(MultipartBodyLengthLimit = 1073741824)]

Views/Shared/_ImageCropper.cshtml
<link rel="stylesheet" href="~/cropperjs/docs/css/cropper.css">
<script src="~/cropperjs/docs/js/cropper.js"></script>

<script>
    var cropperX = null;
    function InitializeCropper(ImageToCropSrcID, CropButtonSrcID,FinalImageSrcID,FinalImageDataSrcID,ResultDivID,ReCropButtonID) {
       //debugger;
        let ImageToCrop = document.querySelector('#' + ImageToCropSrcID);
        //var CroppedDataStatus = document.querySelector('#'+CroppedDataStatus);
        //var cropBoxData = document.querySelector('#cropBoxData');
        let button = document.getElementById(CropButtonSrcID);
        var result = document.getElementById(FinalImageDataSrcID);
        let ReCropButton = document.getElementById(ReCropButtonID);
        var ResultDiv = ResultDivID;
        var ImageToRecrop;
   
        if (cropperX != null) {
            cropperX.destroy();
        }

        cropperX = new Cropper(ImageToCrop, {
            maxWidth: 1200,
            maxHeight: 1200,
            fillColor: '#fff',
            imageSmoothingEnabled: true,
            imageSmoothingQuality: 'high',
            ready: function (event) {
                // Zoom the image to its natural size
                //cropperX.zoomTo(1);
            },

            crop: function (event) {
                //CroppedDataStatus.textContent = JSON.stringify(cropperX.getData());
                //cropBoxData.textContent = JSON.stringify(cropperX.getCropBoxData());
                 
            },

            zoom: function (event) {
                // Keep the image in its natural size
                if (event.detail.oldRatio === 1) {
                    event.preventDefault();
                }
            },
        });

        button.onclick = function () {
           //debugger;
            // result.appendChild(cropperX.getCroppedCanvas());
            var ImageFinalData = cropperX.getCroppedCanvas().toDataURL();
          
            ImageToRecrop = ImageFinalData;
            //document.getElementById(FinalImageSrcID).src = ImageFinalData;
            result.src = ImageFinalData;;


            document.getElementById(FinalImageSrcID).value = ImageFinalData;
            $("#" + ResultDiv).css("display", "block");
            $("#" + CropButtonSrcID).css("display", "none");
             $("#" + ReCropButtonID).css("display", "block");
             if (cropperX != null) {
                cropperX.destroy();
            }
            //cropperX.getCroppedCanvas().toBlob(function (blob) {
            //   //debugger;
            //    //var formData = new FormData();
            //    document.getElementById("MyForm").append('upload', blob, 'imagetest.jpeg');
            //});

        };
        ReCropButton.onclick = function () {
           //debugger;
        $("#" + CropButtonSrcID).css("display", "block");
        $("#" + ImageToCropSrcID).css("display", "block");
        $("#" + ReCropButtonID).css("display", "none");
               if (ImageToRecrop) {


                document.getElementById(ImageToCropSrcID).src = ImageToRecrop;
                //cropperX.cropper('replace', e.target.result);
                InitializeCropper(ImageToCropSrcID, CropButtonSrcID,FinalImageSrcID,FinalImageDataSrcID,ResultDivID,ReCropButtonID);

        }

        };
    }


    function SelectImage(input, ImageToCropSrcID, CropButtonSrcID,FinalImageSrcID, FinalImageDataSrcID,ResultDivID,ReCropButtonID) {

       //debugger;
        $("#" + CropButtonSrcID).css("display", "block");
        $("#" + ImageToCropSrcID).css("display", "block");
         // $("#" + ReCropButtonID).css("display", "block");
     
        
        if (input.files && input.files[0]) {
            let reader = new FileReader();

            reader.onload = function (e) {

                document.getElementById(ImageToCropSrcID).src = e.target.result;
                //cropperX.cropper('replace', e.target.result);
                InitializeCropper(ImageToCropSrcID, CropButtonSrcID,FinalImageSrcID,FinalImageDataSrcID,ResultDivID,ReCropButtonID);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    function RemoveImage(ResultImageDiv,ResultImageID,FileUpload,RecropButtonID,FinalImageSrcID)
    {
       //debugger;
      
        $("#" + ResultImageDiv).css("display", "none");
       
         if (cropperX != null) {
            cropperX.destroy();
        }
        var ImageToCrop = $("#" + ResultImageID);
        var RecropButton = $("#" + RecropButtonID);
        var FinalImage = $("#" + FinalImageSrcID);
        ImageToCrop.attr('src', '');
        FinalImage.val('');
        ImageToCrop.css('display', 'none');
        RecropButton.css('display', 'none');
        document.getElementById(FileUpload).value = "";
        //readURLIndexImage(ResultImageID);
    }

    //InitializeCropper("ImageToCrop","FinalImageID","CropButtonOne");

</script>

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LegalHunter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LegalHunter</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LegalHunter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout-Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LegalHunter</title>
    <!-- icon -->
    <link rel="icon" href="~/favicon.ico">

    <link rel="stylesheet" type="text/css" href="~/LoginTemplate/vendor/bootstrap/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="~/LoginTemplate/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="~/LoginTemplate/vendor/animate/animate.css">

    <link rel="stylesheet" type="text/css" href="~/LoginTemplate/vendor/css-hamburgers/hamburgers.min.css">

    <link rel="stylesheet" type="text/css" href="~/LoginTemplate/vendor/select2/select2.min.css">

    <link rel="stylesheet" type="text/css" href="~/LoginTemplate/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/LoginTemplate/css/main.css">
</head>
<body>
    <style>
        .btn-primary {
    color: #fff;
    background-color: #138270;
    border-color: #138270;
    }

    .btn-primary.active, .btn-primary:active, .show>.btn-primary.dropdown-toggle {
        background-color: #48BFAC;
        background-image: none;
        border-color: #48BFAC
    }

    .btn-primary:hover {
        color: #fff;
        background-color: #48BFAC;
        border-color: #48BFAC
    }
    .btn-primary.active, .btn-primary:active, .show>.btn-primary.dropdown-toggle {
        background-color: #48BFAC;
        background-image: none;
        border-color: #48BFAC
    }
    textarea:focus, input:focus {
    border-color: #48BFAC !important;
}
    </style>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/logo.jpg" alt="IMG">
                </div>
                    @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/LoginTemplate/vendor/jquery/jquery-3.2.1.min.js"></script>

    <script src="~/LoginTemplate/vendor/bootstrap/js/popper.js"></script>
    <script src="~/LoginTemplate/vendor/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/LoginTemplate/vendor/select2/select2.min.js"></script>

    <script src="~/LoginTemplate/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>



    <script src="~/LoginTemplate/js/main.js"></script>
    <script src="~/AdminTemplate/js/jquery.min.js"></script>

    <!-- end screpting -->
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using LegalHunter.Data;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LegalHunter</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800,900" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="@Url.ContentVersioned("~/AdminTemplate/css/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.ContentVersioned("~/AdminTemplate/css/app.css")">
    <!-- icon -->
    <link rel="icon" href="@Url.ContentVersioned("~/favicon.ico")">
    <link href="@Url.ContentVersioned("~/select2.min.css")" rel="stylesheet" />
    <script src="@Url.ContentVersioned("~/AdminTemplate/js/jquery.min.js")"></script>
    <!-- Using the jquery dataTables CSS CDN -->
    <link href="@Url.ContentVersioned("//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css")" rel="stylesheet" asp-append-version="true" />
    <script src="@Url.ContentVersioned("//cdn.datatables.net/1.10.15/js/jquery.dataTables.js")"></script>

    <style>
        .bottomNewBtn {
            float: right !important;
            padding-top: 5px !important;
        }

        .fa-trash {
            color: white !important;
        }
        .bootbox .modal-content {
            margin: auto;
            width: 85%;
        }
        .btn-warning {
            color: #fff;
            background-color: #ffc107;
            border-color: #ffc107;
        }
        .btn-danger {
            color: #fff;
            background-color: #dc3545;
            border-color: #dc3545;
        }
        .btn{
            margin-top:2px;
        }
        .btn-success {
            color: #fff;
            background-color: #28a745;
            border-color: #28a745;
        }
        .btn-primary {
            color: #fff;
            background-color: #138270;
            border-color: #138270;
            box-shadow: 0px 4px 5px 0px #4fd6a7;
        }

        .btn-primary.active, .btn-primary:active, .show>.btn-primary.dropdown-toggle {
            background-color: #48BFAC;
            background-image: none;
            border-color: #48BFAC;
        }

        .btn-primary:hover {
            color: #fff;
            background-color: #48BFAC;
            border-color: #48BFAC;
        }
        .btn-primary.active, .btn-primary:active, .show>.btn-primary.dropdown-toggle {
            background-color: #48BFAC;
            background-image: none;
            border-color: #48BFAC;
        }
        .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
            background-color: #48BFAC;
        }
        a {
        color: #fff;
        }
        a:focus, a:hover {
            color: #FFE588;
        }
        table.dataTable.no-footer {
            border-bottom: 1px solid #138270;
        }
        .dataTables_wrapper.no-footer .dataTables_scrollBody {
            border-bottom: 1px solid #138270;
        }
        table.dataTable thead th, table.dataTable thead td {
            border-bottom: 1px solid #138270;
        }
    </style>
</head>
<body>
    <!-- start admin -->
    <section id="admin">
        <!-- start sidebar -->
        <div class="sidebar">
            <!-- start with head -->
            <div class="head">
                <div class="logo">
                    <img src="~/logo.jpg" alt="">
                </div>
                <a href="#" class="btn btn-danger">LEGAL HUNTER</a>
            </div>
            <!-- end with head -->
            <!-- start the list -->
            <div id="list">
                <ul class="nav flex-column">
                    <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link active"><i class="fa fa-home"></i>Dashboard</a></li>
                    <!-- end user interface submenu -->
                    <!-- start with charts -->
                    <!-- end with charts -->
                    <li class="nav-item"><a asp-area="" asp-controller="Exams" asp-action="ExamList" class="nav-link"><i class="fa fa-table"></i>Exams Management</a></li>
                    <li class="nav-item"><a asp-area="" asp-controller="Questions" asp-action="QuestionsList" class="nav-link"><i class="fa fa-edit"></i>Manage Questions</a></li>
                    <li class="nav-item"><a asp-area="" asp-controller="Category" asp-action="CategoryList"  class="nav-link"><i class="fa fa-play"></i>Category List</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-users"></i>User Management</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-bars"></i>Subscription Types</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-adjust"></i>Subscription History</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-money-bill-alt"></i>Invoices</a></li>

                </ul>
            </div>
            <!-- end the list -->
        </div>
        <!-- end sidebar -->
        <!-- start content -->
        <div class="content">
            <!-- start content head -->
            <div class="head">
                <!-- head top -->
                <div class="top">
                    <div class="left">
                        <button id="on" class="btn btn-info"><i class="fa fa-bars"></i></button>
                        <button id="off" class="btn btn-info hide"><i class="fa fa-align-left"></i></button>
                        @*<button class="btn btn-info hidden-xs-down"><i class="fa fa-expand-arrows-alt"></i></button>
                            <button class="btn btn-info hidden-xs-down"><i class="fa fa-home"></i>Back Home</button>*@
                    </div>
                    <div class="right">
                        <button class="btn btn-info hidden-xs-down"><i class="fa fa-bell"></i></button>
                        @*<button class="btn btn-info hidden-xs-down"><i class="fa fa-envelope"></i></button>*@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="dropdown">
                                <button class="btn btn-info dropdown-toggle" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</button>
                                <div class="dropdown-menu" aria-labelledby="userDropdown">
                                    <a class="dropdown-item" href="#">profile</a>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout">log out</a>
                                </div>
                            </div>
                        }
                    </div>

                </div>
                <!-- end head top -->


            </div>
            <!-- end content head -->
            <!-- start with the real content -->
            <div id="real">

                @RenderBody()

            </div>
            <!-- end the real content -->
        </div>
        <!-- end content -->
    </section>
    <!-- end admin -->
    <!-- start screpting -->

    <script src="~/AdminTemplate/js/tether.min.js"></script>
    <script src="~/AdminTemplate/js/bootstrap.min.js"></script>
    <script src="~/AdminTemplate/js/highcharts.js"></script>
    <script src="~/AdminTemplate/js/chart.js"></script>
    <script src="~/AdminTemplate/js/app.js"></script>

    <script src="~/select2.full.min.js"></script>
    <script src="~/select2.min.js"></script>
    <script src="~/bootbox.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script>
      //toaster notification
        function Notification(Content, Color) {
            debugger
            //var value = '<div class="toast hide toast-3s" role="alert" aria-live="assertive" data-delay="5000" aria-atomic="true" style="position: fixed;bottom: 40px;z-index: 10000;border-radius: 6px;padding: 10px;color:#fff;right: 40px;background: ' + Color + ';box-shadow: 0px 1px 20px 1px #5f5e5ec2;min-width:350px;border: none;font-size: 15px;max-width: 400px;letter-spacing:.4px;">' +
            //    '<div class="toast-body" ><button type="button" class=" close" data-dismiss="toast" aria-label="Close" style="float:right;    margin: 0 5px;"><span style="color: white;">&times;</span></button>' + Content + '</div></div>'

            var value = '<div class="alert" style="position: fixed;bottom: 40px;z-index: 10000;border-radius: 6px;padding: 10px;color:#fff;right: 40px;background: ' + Color + ';box-shadow: 0px 1px 20px 1px #5f5e5ec2;min-width:350px;border: none;font-size: 15px;max-width: 400px;letter-spacing:.4px;" role="alert">'+
      					'<span>'+ Content +'.</span>'+
      					'</div >';
            if (value != null && value != "") {
                $("div.toast-3s").remove();
            }
            $("body").append(value);
            $('.toast-3s').toast('show')

        }
      //end

        $(document).ready(function () {
            @Html.Raw(TempData["AlertStatus"])
            $('.Select2').select2();

        });

        function LoadConfirm(Path, e, type) {

            var currentForm = e;
            var ConfirmMessage = '';
            var ConfirmMessageTitle = '';
            if (type == "delete") {
                ConfirmMessage = 'Confirm to delete this file, as this action cant be reversed.';
                /**/
                ConfirmMessageTitle = 'Delete Data';
                /**/
            }

            e.preventDefault();
            bootbox.dialog({
                title: ConfirmMessageTitle,
                message: '<p>' + ConfirmMessage + '</p>',
                size: 'medium',
                onEscape: true,
                backdrop: true,
                buttons: {

                    fo: {
                        label: 'Proceed',
                        className: 'btn-success',
                        callback: function () {
                            window.location.href = '../' + Path;

                        }
                    },
                    fum: {
                        label: 'Cancel',
                        className: 'btn-danger',
                        callback: function () {

                        }
                    }
                }
            })
        };
    </script>

    <!-- end screpting -->
    @RenderSection("Scripts", required: false)
</body>
</html>